#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

[ -z "$BCFDKCOFPATH" ] && export BCFDKCOFPATH=$(while cd ..; do if [ -e "buildNclean.sh" ]; then pwd -P; break ; elif [ "$PWD" = "/" ]; then break; fi; done)

[ -n "$BCFDKCOFPATH" ] && source $BCFDKCOFPATH/scripts/bCFDK_CoF_Checks && checkIfItShouldBuild

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

set -x

wmake $targetType foamToVTKBCFDK
wmake $targetType

#------------------------------------------------------------------------------
